@echo off
echo Starting all Wheels24Drive Backend Services...

echo 1. Starting User Profile (Port 5006)...
start "User Profile (5006)" cmd /k "cd 1._user_profile\backend && npm install && node server.js"

echo 2. Starting OTP Verification Server (Port 5000)...
start "OTP Server (5000)" cmd /k "cd 2._otp_verification\backend && npm install && node server.js"

echo 3. Starting Vehicle Management Server (Port 5001)...
start "Vehicle Server (5001)" cmd /k "cd 3._vehicle_management\backend && npm install && node server.js"

echo 4. Starting Subscriptions Server (Port 5003)...
start "Subscriptions Server (5003)" cmd /k "cd 4._subscriptions\backend && npm install && node server.js"

echo 5. Starting Bidding Server (Port 5002)...
start "Bidding Server (5002)" cmd /k "cd 5._bidding\backend && npm install && node server.js"

echo 6. Starting Notifications Server (Port 5004)...
start "Notifications Server (5004)" cmd /k "cd 6._notifications\backend && npm install && node server.js"

echo 7. Starting Watchlist Server (Port 5005)...
start "Watchlist Server (5005)" cmd /k "cd 7._watchlist\backend && npm install && node server.js"

echo All backend servers are starting in new windows!
pause
